# -*- coding: utf-8 -*-
"""Logistic_Regression_COVID_tidied_up.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HO-fTtV-REze7F6HfvnlP3-Rd10PlKFr
"""

from google.colab import files
uploaded_file = files.upload()

# ΒΗΜΑ 1 Φορτώνω τα δεδομένα
import pandas as pd  # Βιβλιοθηκη η οποια διαβαζει το τι περιέχει ένα αρχείο
 
# με την read_csv διαβαζουμε τι περιεχει ενα .csv αρχειο, εδω της δειχνουμε να δαιβασει το αρχείο: Covid-Dataset-with-numbers.csv 
mydata = pd.read_csv('Covid-Dataset-with-numbers.csv')

# ΒΗΜΑ 2 Διαχωρίζω τα δεδομένα σε δεδομένα που αφορούν τα συμπτώματα(features ή χαρακτηριστικά) και σε δεδομένα που αφορούν την διάγνωση(target ή στόχος)

# Απο τα δεδομένα πάρε όλες τις στήλες εκτός της στήλης 'COVID-19'
myFeatures = mydata.loc[:, mydata.columns != 'COVID-19']  # Συμπτώματα

# Απο τα δεδομένα πάρε μόνο την στήλη 'COVID-19'
myTargets = mydata.loc[:, mydata.columns == 'COVID-19']  # Διάγνωση

# ΒΗΜΑ 3 Χωρίζω τα συμπτώματα και τις διαγώνσεις σε δυο σετ, ένα για εκπαίδευη(training set) και ένα για τεστάρισμα(testing set)

# Με την βιβλιοθηκη αυτή σπάμε τα δεδομένα στα δυο σετ που αναφέραμε πιο πάνω
from sklearn.model_selection import train_test_split

# Τα δυο σετ ειναι: 
# Πρώτο σετ(training set)  ->  x_train(συμπτώματα), y_train(διαγνώσεις)
# Δευτερο σετ(testing set) ->  x_test(συμπτώματα) , y_test(διαγνώσεις)
x_train, x_test, y_train, y_test = train_test_split(myFeatures, myTargets, test_size=0.25, random_state=0)

# ΒΗΜΑ 4 Εκπαίδευση του αλγορίθμου μας

# απο την βιβλιοθήκη αυτή εδώ, φέρε την μέθοδο Logistic Regression
from sklearn.linear_model import LogisticRegression 

# Χρησιμοποιούμε την μέθοδο του Logistic Regression για να προβλέψουμε αν κάποιος/α έχει ή δεν έχε COVID-19 βάση των συμπτωμάτων του/της
logisticRegr = LogisticRegression()

# Ελπαίδευση του προγράμματος μας, του λέμε να κάνει fit("ταιριάξει") τα δεδεδομένα και να προσπαθήσει να προβλέψει αν οι ασθενείς έχουν ή δεν έχουν COVID-19
logisticRegr.fit(x_train, y_train.values.ravel())